/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import atores.*;
import javax.swing.JOptionPane;
import login.ControladorLogin;
import login.ControladorLoginInterface;

/**
 *
 * @author steph
 */
public class InterfaceLogin extends javax.swing.JFrame {

    int mudouLogin;
    int mudouSenha;
    ControladorLoginInterface controle;
    private JOptionPane caixaDialogo;
    
    
    /**
     * Creates new form InterfaceSecretaria
     */
    public InterfaceLogin() {
        initComponents();
        mudouLogin = 0;
        caixaDialogo = new JOptionPane();
    }
    
    public InterfaceLogin(ControladorLoginInterface controle)
    {
        initComponents();
        mudouLogin = 0;
        this.controle = controle;
        caixaDialogo = new JOptionPane();
    }

    public void mostrarMsg(String msg)
    {
        caixaDialogo.showMessageDialog(null, msg);
    }
    
    public void fechar()
    {
        this.setVisible(false);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        cxtUsuario = new javax.swing.JTextField();
        cxtSenha = new javax.swing.JPasswordField();
        cxsTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cxtUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cxtUsuario.setText("Usuário");
        cxtUsuario.setToolTipText("");
        cxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxtUsuarioFocusLost(evt);
            }
        });
        cxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtUsuarioActionPerformed(evt);
            }
        });

        cxtSenha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cxtSenha.setText("jPasswordField1");
        cxtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cxtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cxtSenhaFocusLost(evt);
            }
        });
        cxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtSenhaActionPerformed(evt);
            }
        });

        cxsTipo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cxsTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Selecione >", "Médico", "Paciente", "Secretária" }));
        cxsTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxsTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cxsTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cxtUsuario)
                        .addComponent(cxtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(cxsTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ico_peq.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 0, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Clinica Médica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtUsuarioActionPerformed

    private void cxsTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxsTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxsTipoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String senha = String.valueOf( cxtSenha.getPassword());
        controle.efetuarLogin( cxtUsuario.getText(), senha );
                
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cxtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxtUsuarioFocusGained
        // TODO add your handling code here:
        if ( mudouLogin == 0 )
            cxtUsuario.setText("");
    }//GEN-LAST:event_cxtUsuarioFocusGained

    private void cxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxtUsuarioFocusLost
        // TODO add your handling code here:
        if ( cxtUsuario.getText().equals("") )
        {
            cxtUsuario.setText("Usuário");
            mudouLogin = 0;
        }
        else
            mudouLogin = 1;
            
    }//GEN-LAST:event_cxtUsuarioFocusLost

    private void cxtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxtSenhaFocusGained
        // TODO add your handling code here:
        if ( mudouSenha == 0 )
            cxtSenha.setText("");
    }//GEN-LAST:event_cxtSenhaFocusGained

    private void cxtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cxtSenhaFocusLost
        // TODO add your handling code here:
        if ( cxtSenha.getText().equals("") )
        {
            cxtSenha.setText("***************");
            mudouSenha = 0;
        }
        else
            mudouSenha = 1;

    }//GEN-LAST:event_cxtSenhaFocusLost

    private void cxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        Usuario sec0 = new SuperSec( "supersec", "1234", "Super Secretária" , "XXXXXX" , "/imagens/secretaria01.png" );
        Usuario sec1 = new Secretaria( "sec1", "1234", "Maria das Dores" , "198987" , "/imagens/secretaria01.png" );
        Usuario sec2 = new Secretaria( "sec2", "5678", "Jereka Del Mare" , "222666" , "/imagens/secretaria02.png" );

        Usuario pac1 = new Paciente( "honor77", "730%", "Seu Honorato Gancho" , "800.844.943-87" , "/imagens/paciente01.png" );
        
        ControladorLogin controle = new ControladorLogin();
        controle.addUsuario(sec0);
        controle.addUsuario(sec1);
        controle.addUsuario(sec2);
        controle.addUsuario(pac1);

        InterfaceLogin login = controle.getTelaLogin();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new InterfaceLogin().setVisible(true);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cxsTipo;
    private javax.swing.JPasswordField cxtSenha;
    private javax.swing.JTextField cxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
